[book]
title = "The Programmer's Compendium"
author = "Qasim K"
description = "My knowledge relating to software engineering."
language = "en-GB"

[output.html]
site-url = "/programmers-compendium/"
git-repository-url = "https://github.com/QasimK/programmers-compendium"
